import type { LucideIcon } from "lucide-react";

export function Panel({icon:Icon,title,description,children}:{icon:LucideIcon;title:string;description:string;children:React.ReactNode}){return <section className="rounded-[28px] border border-white/10 bg-white/[.025] p-6 sm:p-8"><Icon className="workspace-accent size-6"/><h2 className="mt-5 text-2xl font-bold">{title}</h2><p className="mt-2 text-sm leading-7 text-white/45">{description}</p><div className="mt-6">{children}</div></section>}
export function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="block"><span className="mb-2 block text-sm font-bold text-white/75">{label}</span><input {...props} className="min-h-12 w-full rounded-xl border border-white/10 bg-black/25 px-4 text-base outline-none focus:border-[var(--workspace-accent)]"/></label>}
export function Select({label,children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className="block"><span className="mb-2 block text-sm font-bold text-white/75">{label}</span><select {...props} className="min-h-12 w-full rounded-xl border border-white/10 bg-[#0b0808] px-4 text-base">{children}</select></label>}
export function Textarea({label,...props}:React.TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string}){return <label className="block"><span className="mb-2 block text-sm font-bold text-white/75">{label}</span><textarea {...props} className="min-h-28 w-full rounded-xl border border-white/10 bg-black/25 p-4 text-base outline-none focus:border-[var(--workspace-accent)]"/></label>}
export function Submit({children,danger=false}:{children:React.ReactNode;danger?:boolean}){return <button className={`min-h-12 rounded-xl px-5 text-sm font-bold ${danger?"border border-red-300/20 bg-red-300/10 text-red-100":"workspace-theme-button text-[#050303]"}`}>{children}</button>}
export function Notice({saved,error}:{saved?:string;error?:string}){return <>{saved?<p className="mt-6 rounded-2xl border border-emerald-300/20 bg-emerald-300/8 p-4 text-sm text-emerald-100">Changes saved successfully.</p>:null}{error?<p className="mt-6 rounded-2xl border border-red-300/20 bg-red-300/8 p-4 text-sm text-red-100">That change could not be saved. Check the values and your permission.</p>:null}</>}
export function Empty({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-dashed border-white/12 p-8 text-center text-sm leading-7 text-white/40">{children}</div>}
export function Row({title,subtitle,meta,action}:{title:string;subtitle?:string|null;meta?:string;action?:React.ReactNode}){return <div className="flex flex-col gap-4 border-b border-white/7 py-5 last:border-0 sm:flex-row sm:items-center"><div className="min-w-0"><p className="font-bold">{title}</p>{subtitle?<p className="mt-1 text-sm text-white/42">{subtitle}</p>:null}</div>{meta?<span className="rounded-full border border-white/8 px-3 py-1 text-xs font-bold text-white/48 sm:ml-auto">{meta}</span>:null}{action}</div>}
