import { activityCommand } from "./activity.js";
import { applicationsCommand } from "./applications.js";
import { auditCommand } from "./audit.js";
import { helpCommand } from "./help.js";
import { linkCommand } from "./link.js";
import { pingCommand } from "./ping.js";
import { quotaCommand } from "./quota.js";
import { rankCommand } from "./rank.js";
import { statusCommand } from "./status.js";
import { workspaceCommand } from "./workspace.js";
import { setupCommand } from "./setup.js";
import { diagnosticsCommand } from "./diagnostics.js";
import { unlinkCommand } from "./unlink.js";
import { setrankCommand } from "./setrank.js";
import { userCommand } from "./user.js";
import { staffCodeCommand } from "./staff-code.js";
import { supportCommand } from "./support.js";

export const commands = [helpCommand, setupCommand, diagnosticsCommand, unlinkCommand, pingCommand, linkCommand, statusCommand, workspaceCommand, userCommand, auditCommand, rankCommand, setrankCommand, activityCommand, quotaCommand, applicationsCommand, staffCodeCommand, supportCommand];
export const commandMap = new Map(commands.map((command) => [command.data.name, command]));
