"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getRobloxGroupDetails } from "@/lib/roblox-groups";
import { listRobloxGroups } from "@/lib/roblox-membership";

export type LinkCodeState={code?:string;expiresAt?:string;error?:string};
async function context(publicId:string){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/login?next=/dashboard/${publicId}`);const{data,error}=await supabase.rpc("workspace_control_state",{target_public_id:publicId});if(error||!data)redirect("/dashboard");return{supabase,user,state:data as unknown as {workspace:{id:string;role:string;operational_status:string}}}}

export async function createDiscordCode(_state:LinkCodeState,formData:FormData):Promise<LinkCodeState>{const publicId=String(formData.get("public_id")||"");const{supabase,state}=await context(publicId);const{data,error}=await supabase.rpc("create_discord_link_code",{target_workspace_id:state.workspace.id});if(error)return{error:error.message.includes("suspended")?"Workspace connections are locked while restricted.":"Could not create a link code."};const result=data as {code?:string;expires_at?:string}|null;return result?.code?{code:result.code,expiresAt:result.expires_at}:{error:"Could not create a link code."}}

export async function connectRobloxGroup(formData:FormData){const publicId=String(formData.get("public_id")||"");const groupId=String(formData.get("group_id")||"").trim();if(!/^\d+$/.test(groupId))redirect(`/dashboard/${publicId}/connections?error=invalid_group`);const{supabase,user,state}=await context(publicId);if(!["owner","admin"].includes(state.workspace.role))redirect(`/dashboard/${publicId}/connections?error=manager_required`);const details=await getRobloxGroupDetails(groupId);if(!details)redirect(`/dashboard/${publicId}/connections?error=group_not_found`);
  const{data:link}=await supabase.from("account_links").select("provider_user_id").eq("user_id",user.id).eq("provider","roblox").maybeSingle();
  if(link){const groups=await listRobloxGroups(link.provider_user_id);const owned=groups.ok?groups.groups.find(g=>g.id===groupId&&g.roleRank===255):null;if(!owned)redirect(`/dashboard/${publicId}/connections?error=group_owner_required`)}
  const{error}=await supabase.rpc("set_workspace_roblox_group",{target_workspace_id:state.workspace.id,group_id:details.id,group_name:details.name,icon_url:details.iconUrl||"",oauth_verified:Boolean(link)});
  if(error)redirect(`/dashboard/${publicId}/connections?error=save_failed`);revalidatePath(`/dashboard/${publicId}`);redirect(`/dashboard/${publicId}/connections?saved=roblox`)}

export async function saveWorkspaceAccess(formData:FormData){const publicId=String(formData.get("public_id")||"");const rankMin=Number(formData.get("rank_min"));const roleIds=String(formData.get("role_ids")||"").split(",").map(v=>v.trim()).filter(v=>/^\d+$/.test(v));const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("save_workspace_settings",{target_workspace_id:state.workspace.id,rank_min:rankMin,role_ids:roleIds});if(error)redirect(`/dashboard/${publicId}/settings?error=settings_failed`);revalidatePath(`/dashboard/${publicId}`);redirect(`/dashboard/${publicId}/settings?saved=access`)}

export async function saveWorkspaceTheme(formData:FormData){const publicId=String(formData.get("public_id")||"");const mode=String(formData.get("theme_mode")||"");const start=String(formData.get("theme_color_start")||"").toLowerCase();const requestedEnd=String(formData.get("theme_color_end")||"").toLowerCase();const end=mode==="solid"?start:requestedEnd;if(!["solid","gradient"].includes(mode)||!/^#[0-9a-f]{6}$/.test(start)||!/^#[0-9a-f]{6}$/.test(end))redirect(`/dashboard/${publicId}/settings?error=theme_invalid`);const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("save_workspace_theme",{target_workspace_id:state.workspace.id,requested_theme_mode:mode,requested_color_start:start,requested_color_end:end});if(error)redirect(`/dashboard/${publicId}/settings?error=theme_failed`);revalidatePath(`/dashboard/${publicId}`,"layout");redirect(`/dashboard/${publicId}/settings?saved=theme`)}

function value(formData:FormData,key:string){return String(formData.get(key)||"").trim()}
async function finish(publicId:string,path:string,error:unknown){if(error)redirect(`/dashboard/${publicId}/${path}?error=save_failed`);revalidatePath(`/dashboard/${publicId}/${path}`);redirect(`/dashboard/${publicId}/${path}?saved=1`)}

export async function updateWorkspaceProfile(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("update_workspace_profile",{target_workspace_id:state.workspace.id,requested_name:value(formData,"name")});await finish(publicId,"settings",error)}
export async function inviteMember(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("invite_workspace_member",{target_workspace_id:state.workspace.id,target_email:value(formData,"email"),requested_role:value(formData,"role")});await finish(publicId,"members",error)}
export async function manageMember(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("manage_workspace_member",{target_workspace_id:state.workspace.id,target_user_id:value(formData,"user_id"),requested_role:value(formData,"role"),requested_action:value(formData,"action")});await finish(publicId,"members",error)}
export async function transferOwnership(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("transfer_workspace_ownership",{target_workspace_id:state.workspace.id,target_user_id:value(formData,"user_id")});if(error)redirect(`/dashboard/${publicId}/settings?error=transfer_failed`);redirect("/dashboard")}
export async function setWorkspaceLifecycle(formData:FormData){const publicId=value(formData,"public_id");const action=value(formData,"action");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("set_workspace_lifecycle",{target_workspace_id:state.workspace.id,requested_action:action,confirmation_name:value(formData,"confirmation_name")});if(error)redirect(`/dashboard/${publicId}/settings?error=lifecycle_failed`);redirect("/dashboard")}
export async function disconnectIntegration(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("disconnect_workspace_integration",{target_workspace_id:state.workspace.id,target_provider:value(formData,"provider")});await finish(publicId,"connections",error)}

export async function saveRankBinding(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const payload={workspace_id:state.workspace.id,roblox_role_id:value(formData,"roblox_role_id"),roblox_role_name:value(formData,"roblox_role_name"),discord_role_id:value(formData,"discord_role_id")||null,discord_role_name:value(formData,"discord_role_name")||null,minimum_activity_minutes:Number(value(formData,"minimum_activity_minutes")||0),cooldown_minutes:Number(value(formData,"cooldown_minutes")||0),requires_approval:formData.get("requires_approval")==="on"};const{error}=await supabase.from("rank_bindings").upsert(payload,{onConflict:"workspace_id,roblox_role_id"});await finish(publicId,"ranking",error)}
export async function deleteRankBinding(formData:FormData){const publicId=value(formData,"public_id");const{supabase}=await context(publicId);const{error}=await supabase.from("rank_bindings").delete().eq("id",value(formData,"id"));await finish(publicId,"ranking",error)}
export async function saveQuota(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const payload={workspace_id:state.workspace.id,roblox_role_id:value(formData,"roblox_role_id"),period:value(formData,"period"),minutes_required:Number(value(formData,"minutes_required")),grace_minutes:Number(value(formData,"grace_minutes")||0)};const{error}=await supabase.from("activity_quotas").upsert(payload,{onConflict:"workspace_id,roblox_role_id,period"});await finish(publicId,"activity",error)}
export async function addManualActivity(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const minutes=Math.max(1,Number(value(formData,"minutes")||0));const ended=new Date();const started=new Date(ended.getTime()-minutes*60000);const{error}=await supabase.from("activity_sessions").insert({workspace_id:state.workspace.id,roblox_user_id:value(formData,"roblox_user_id"),roblox_username:value(formData,"roblox_username"),started_at:started.toISOString(),ended_at:ended.toISOString(),duration_seconds:minutes*60,source:"manual"});await finish(publicId,"activity",error)}
export async function createApplicationForm(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const fields=value(formData,"questions").split("\n").map((label,i)=>({id:`q${i+1}`,label:label.trim(),type:"text",required:true})).filter(q=>q.label);const{error}=await supabase.from("application_forms").insert({workspace_id:state.workspace.id,name:value(formData,"name"),description:value(formData,"description")||null,target_role_name:value(formData,"target_role_name")||null,status:value(formData,"status")||"draft",fields,created_by:user.id});await finish(publicId,"applications",error)}
export async function createAutomation(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const{error}=await supabase.from("automations").insert({workspace_id:state.workspace.id,name:value(formData,"name"),trigger_type:value(formData,"trigger_type"),enabled:formData.get("enabled")==="on",definition:{action:value(formData,"action"),channel_id:value(formData,"channel_id")||null},created_by:user.id});await finish(publicId,"automations",error)}
export async function deleteRecord(formData:FormData){const publicId=value(formData,"public_id");const table=value(formData,"table") as "activity_quotas"|"application_forms"|"automations"|"departments"|"community_sessions"|"leave_requests"|"workspace_tasks"|"knowledge_entries"|"announcement_templates"|"workspace_roblox_groups";const path=value(formData,"path");const allowed=["activity_quotas","application_forms","automations","departments","community_sessions","leave_requests","workspace_tasks","knowledge_entries","announcement_templates","workspace_roblox_groups"];if(!allowed.includes(table))redirect(`/dashboard/${publicId}`);const{supabase}=await context(publicId);const{error}=await supabase.from(table).delete().eq("id",value(formData,"id"));await finish(publicId,path,error)}

export async function createDepartment(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.from("departments").insert({workspace_id:state.workspace.id,name:value(formData,"name"),description:value(formData,"description")||null,discord_role_id:value(formData,"discord_role_id")||null,roblox_group_id:value(formData,"roblox_group_id")||null});await finish(publicId,"operations",error)}
export async function createCommunitySession(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const{error}=await supabase.from("community_sessions").insert({workspace_id:state.workspace.id,session_type:value(formData,"session_type"),title:value(formData,"title"),starts_at:new Date(value(formData,"starts_at")).toISOString(),host_user_id:user.id,discord_channel_id:value(formData,"discord_channel_id")||null,notes:value(formData,"notes")||null});await finish(publicId,"operations",error)}
export async function createLeaveRequest(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.from("leave_requests").insert({workspace_id:state.workspace.id,member_name:value(formData,"member_name"),starts_on:value(formData,"starts_on"),ends_on:value(formData,"ends_on"),reason:value(formData,"reason")});await finish(publicId,"operations",error)}
export async function createWorkspaceTask(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const due=value(formData,"due_at");const{error}=await supabase.from("workspace_tasks").insert({workspace_id:state.workspace.id,title:value(formData,"title"),description:value(formData,"description")||null,priority:value(formData,"priority")||"normal",due_at:due?new Date(due).toISOString():null,created_by:user.id});await finish(publicId,"operations",error)}
export async function createKnowledgeEntry(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const{error}=await supabase.from("knowledge_entries").insert({workspace_id:state.workspace.id,entry_type:value(formData,"entry_type"),title:value(formData,"title"),content:value(formData,"content"),visibility:value(formData,"visibility"),created_by:user.id});await finish(publicId,"knowledge",error)}
export async function createAnnouncementTemplate(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const{error}=await supabase.from("announcement_templates").insert({workspace_id:state.workspace.id,name:value(formData,"name"),announcement_type:value(formData,"announcement_type"),title_template:value(formData,"title_template"),body_template:value(formData,"body_template"),discord_channel_id:value(formData,"discord_channel_id")||null,created_by:user.id});await finish(publicId,"communications",error)}
export async function saveCommunityMessaging(formData:FormData){const publicId=value(formData,"public_id");const{supabase,state}=await context(publicId);const{error}=await supabase.rpc("save_community_messaging",{target_workspace_id:state.workspace.id,requested_welcome_enabled:formData.get("welcome_enabled")==="on",requested_welcome_channel_id:value(formData,"welcome_channel_id"),requested_welcome_message:value(formData,"welcome_message"),requested_goodbye_enabled:formData.get("goodbye_enabled")==="on",requested_goodbye_channel_id:value(formData,"goodbye_channel_id"),requested_goodbye_message:value(formData,"goodbye_message"),requested_nickname_sync_enabled:formData.get("nickname_sync_enabled")==="on",requested_verification_dm_enabled:formData.get("verification_dm_enabled")==="on",requested_role_sync_enabled:formData.get("role_sync_enabled")==="on",requested_member_count_channel_id:value(formData,"member_count_channel_id")});await finish(publicId,"communications",error)}
export async function addWorkspaceRobloxGroup(formData:FormData){const publicId=value(formData,"public_id");const groupId=value(formData,"group_id");if(!/^\d{1,20}$/.test(groupId))redirect(`/dashboard/${publicId}/connections?error=invalid_group`);const details=await getRobloxGroupDetails(groupId);if(!details)redirect(`/dashboard/${publicId}/connections?error=group_not_found`);const{supabase,state}=await context(publicId);const{error}=await supabase.from("workspace_roblox_groups").insert({workspace_id:state.workspace.id,group_id:details.id,group_name:details.name,purpose:value(formData,"purpose")||"community",is_primary:false});await finish(publicId,"connections",error)}
export async function createDashboardRankRequest(formData:FormData){const publicId=value(formData,"public_id");const{supabase,user,state}=await context(publicId);const bindingId=value(formData,"binding_id");const{data:binding,error:bindingError}=await supabase.from("rank_bindings").select("roblox_role_id,roblox_role_name,requires_approval").eq("id",bindingId).eq("workspace_id",state.workspace.id).maybeSingle();if(bindingError||!binding)await finish(publicId,"ranking",bindingError||new Error("binding_missing"));const{error}=await supabase.from("rank_actions").insert({workspace_id:state.workspace.id,target_roblox_user_id:value(formData,"roblox_user_id"),target_username:value(formData,"roblox_username"),requested_by:user.id,to_role_id:binding!.roblox_role_id,to_role_name:binding!.roblox_role_name,reason:value(formData,"reason")||"Dashboard rank request",status:binding!.requires_approval?"pending":"approved",policy_snapshot:{source:"dashboard",requires_approval:binding!.requires_approval}});await finish(publicId,"ranking",error)}
