import Link from "next/link";
import { Activity, ArrowRight, FileClock, ShieldAlert, UsersRound } from "lucide-react";
import { PageHeading } from "@/components/workspace-shell";
import { getWorkspaceControl } from "@/lib/workspace-control";

export const dynamic = "force-dynamic";

export default async function WorkspaceOverview({ params }: { params: Promise<{ workspaceId: string }> }) {
  const { workspaceId } = await params; const { state, supabase } = await getWorkspaceControl(workspaceId); const w=state.workspace;
  const { count: apiKeyCount } = await supabase.from("api_keys").select("id", { count: "exact", head: true }).eq("workspace_id", w.id).is("revoked_at", null);
  const integrations=new Map(state.integrations.map(i=>[i.provider,i.status]));
  return <><PageHeading eyebrow="Workspace overview" title={w.name} description="Your Roblox community, Discord server, members, activity, and game connection in one place." action={<code className="workspace-accent-surface rounded-full border px-4 py-2 text-sm">{w.public_id}</code>} />
    {w.operational_status!=="active"?<section className="mt-7 rounded-3xl border border-red-300/20 bg-red-300/8 p-6"><div className="flex gap-4"><ShieldAlert className="size-6 text-red-200"/><div><h2 className="text-lg font-bold">Workspace {w.moderation_status}</h2><p className="mt-2 text-sm leading-7 text-white/60">{w.moderation_reason}. {w.moderation_expires_at?`Scheduled to end ${formatDate(w.moderation_expires_at)}.`:"No automatic end date."} {w.appeal_allowed?"You may appeal through the Nexora Discord server.":"This action is not eligible for appeal."}</p></div></div></section>:null}
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="Workspace members" value={state.counts.members}/><Metric icon={Activity} label="Rank actions" value={state.counts.rank_actions}/><Metric icon={Activity} label="Activity sessions" value={state.counts.activity_sessions}/><Metric icon={FileClock} label="Recorded events" value={state.counts.log_events}/></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Connections" description="Finish both connections before using live ranking."><Connection provider="discord" href={`/dashboard/${w.public_id}/connections#discord`} name="Discord server" detail={w.discord_guild_name||"Use the bot and /link code"} ready={integrations.get("discord")==="connected"}/><Connection provider="roblox" href={`/dashboard/${w.public_id}/connections#roblox`} name="Roblox group" detail={w.roblox_group_name||"Choose the group you own"} ready={Boolean(w.roblox_group_id)}/><Link href={`/dashboard/${w.public_id}/connections`} className="workspace-accent mt-5 inline-flex items-center gap-2 text-sm font-bold">Manage connections <ArrowRight className="size-4"/></Link></Panel><Panel title="Workspace readiness" description="The essentials required for Discord and in-game use."><Check label="Permanent workspace ID" ready/><Check label="Private API key" ready={Boolean(apiKeyCount)}/><Check label="Discord bot linked" ready={integrations.get("discord")==="connected"}/><Check label="Roblox group selected" ready={Boolean(w.roblox_group_id)}/><Link href={`/dashboard/${w.public_id}/settings`} className="workspace-accent mt-5 inline-flex items-center gap-2 text-sm font-bold">Open settings & API <ArrowRight className="size-4"/></Link></Panel></section></>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:number}){return <article className="min-w-0 rounded-[26px] border border-white/10 bg-white/[.025] p-6"><Icon className="workspace-accent size-5"/><strong className="mt-8 block text-4xl font-extrabold">{value}</strong><span className="mt-2 block text-sm text-white/48">{label}</span></article>}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <article className="rounded-[28px] border border-white/10 bg-white/[.025] p-6 sm:p-8"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/45">{description}</p><div className="mt-6 space-y-3">{children}</div></article>}
function Connection({provider,name,detail,ready,href}:{provider:"discord"|"roblox";name:string;detail:string;ready:boolean;href:string}){const discord=provider==="discord";return <div className="flex items-center gap-4 rounded-2xl border border-white/8 bg-black/20 p-4"><span className={`flex size-12 shrink-0 items-center justify-center rounded-xl ${discord?"bg-[#5865f2] text-white":"bg-white text-black"}`}>{discord?<DiscordMark/>:<RobloxMark/>}</span><div className="min-w-0"><b className="text-base">{name}</b><p className="mt-1 truncate text-sm text-white/42">{detail}</p></div><Link href={href} className={`ml-auto inline-flex min-h-9 shrink-0 items-center justify-center rounded-lg px-4 text-[11px] font-extrabold uppercase tracking-wider transition ${discord?"bg-[#5865f2] text-white hover:bg-[#6875f5]":"bg-white text-black hover:bg-white/85"}`}>{ready?"Manage":"Setup"}</Link></div>}
function DiscordMark(){return <svg viewBox="0 0 24 24" className="size-6" aria-hidden="true"><path fill="currentColor" d="M19.3 5.3A17 17 0 0 0 15.2 4l-.5 1.1a15.6 15.6 0 0 0-5.4 0L8.8 4a17 17 0 0 0-4.1 1.3C2.1 9.1 1.4 12.8 1.8 16.4a16.7 16.7 0 0 0 5 2.5l1.2-1.7c-.7-.3-1.3-.6-1.9-1l.5-.4c3.7 1.7 7.7 1.7 11.3 0l.5.4c-.6.4-1.2.7-1.9 1l1.2 1.7a16.7 16.7 0 0 0 5-2.5c.5-4.2-.8-7.9-3.4-11.1ZM8.8 14.3c-1.1 0-2-1-2-2.2 0-1.2.9-2.2 2-2.2s2 1 2 2.2c0 1.2-.9 2.2-2 2.2Zm6.4 0c-1.1 0-2-1-2-2.2 0-1.2.9-2.2 2-2.2s2 1 2 2.2c0 1.2-.9 2.2-2 2.2Z"/></svg>}
function RobloxMark(){return <svg viewBox="0 0 24 24" className="size-6" aria-hidden="true"><path fill="currentColor" fillRule="evenodd" d="m5.2 2 16.8 3.2L18.8 22 2 18.8 5.2 2Zm5.2 7.1-.9 4.5 4.5.9.9-4.5-4.5-.9Z" clipRule="evenodd"/></svg>}
function Check({label,ready}:{label:string;ready:boolean}){return <div className="flex items-center gap-3 py-2 text-sm"><span className={`size-2 rounded-full ${ready?"bg-[#d79a9a]":"bg-amber-300"}`}/><span className="text-white/68">{label}</span><span className="ml-auto text-xs text-white/35">{ready?"Ready":"Action needed"}</span></div>}
function formatDate(value:string){return new Date(value).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"})+" UTC"}
