import Link from "next/link";
import { Activity, ArrowRight, Bot, FileClock, ShieldAlert, UsersRound } from "lucide-react";
import { PageHeading } from "@/components/workspace-shell";
import { getWorkspaceControl } from "@/lib/workspace-control";

export const dynamic = "force-dynamic";

export default async function WorkspaceOverview({ params }: { params: Promise<{ workspaceId: string }> }) {
  const { workspaceId } = await params; const { state, supabase } = await getWorkspaceControl(workspaceId); const w=state.workspace;
  const { count: apiKeyCount } = await supabase.from("api_keys").select("id", { count: "exact", head: true }).eq("workspace_id", w.id).is("revoked_at", null);
  const integrations=new Map(state.integrations.map(i=>[i.provider,i.status]));
  return <><PageHeading eyebrow="Workspace overview" title={w.name} description="Your Roblox community, Discord server, members, activity, and game connection in one place." action={<code className="rounded-full border border-[#d3aa70]/20 bg-[#d3aa70]/8 px-4 py-2 text-sm text-[#e8c489]">{w.public_id}</code>} />
    {w.operational_status!=="active"?<section className="mt-7 rounded-3xl border border-red-300/20 bg-red-300/8 p-6"><div className="flex gap-4"><ShieldAlert className="size-6 text-red-200"/><div><h2 className="text-lg font-bold">Workspace {w.moderation_status}</h2><p className="mt-2 text-sm leading-7 text-white/60">{w.moderation_reason}. {w.moderation_expires_at?`Scheduled to end ${formatDate(w.moderation_expires_at)}.`:"No automatic end date."} {w.appeal_allowed?"You may appeal through the Nexora Discord server.":"This action is not eligible for appeal."}</p></div></div></section>:null}
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="Workspace members" value={state.counts.members}/><Metric icon={Activity} label="Rank actions" value={state.counts.rank_actions}/><Metric icon={Activity} label="Activity sessions" value={state.counts.activity_sessions}/><Metric icon={FileClock} label="Recorded events" value={state.counts.log_events}/></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Connections" description="Finish both connections before using live ranking."><Connection name="Discord server" detail={w.discord_guild_name||"Use the bot and /link code"} ready={integrations.get("discord")==="connected"}/><Connection name="Roblox group" detail={w.roblox_group_name||"Choose the group you own"} ready={Boolean(w.roblox_group_id)}/><Link href={`/dashboard/${w.public_id}/connections`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#e8c489]">Manage connections <ArrowRight className="size-4"/></Link></Panel><Panel title="Workspace readiness" description="The essentials required for Discord and in-game use."><Check label="Permanent workspace ID" ready/><Check label="Private API key" ready={Boolean(apiKeyCount)}/><Check label="Discord bot linked" ready={integrations.get("discord")==="connected"}/><Check label="Roblox group selected" ready={Boolean(w.roblox_group_id)}/><Link href={`/dashboard/${w.public_id}/settings`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#e8c489]">Open settings & API <ArrowRight className="size-4"/></Link></Panel></section></>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:number}){return <article className="min-w-0 rounded-[26px] border border-white/10 bg-white/[.025] p-6"><Icon className="size-5 text-[#e8c489]"/><strong className="mt-8 block text-4xl font-extrabold">{value}</strong><span className="mt-2 block text-sm text-white/48">{label}</span></article>}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <article className="rounded-[28px] border border-white/10 bg-white/[.025] p-6 sm:p-8"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/45">{description}</p><div className="mt-6 space-y-3">{children}</div></article>}
function Connection({name,detail,ready}:{name:string;detail:string;ready:boolean}){return <div className="flex items-center gap-4 rounded-2xl border border-white/8 bg-black/20 p-4"><span className={`flex size-10 items-center justify-center rounded-xl ${ready?"bg-emerald-300/10 text-emerald-200":"bg-white/5 text-white/40"}`}><Bot className="size-4"/></span><div><b className="text-base">{name}</b><p className="mt-1 text-sm text-white/42">{detail}</p></div><span className="ml-auto text-xs font-bold uppercase tracking-wider text-white/35">{ready?"Ready":"Setup"}</span></div>}
function Check({label,ready}:{label:string;ready:boolean}){return <div className="flex items-center gap-3 py-2 text-sm"><span className={`size-2 rounded-full ${ready?"bg-emerald-400":"bg-amber-300"}`}/><span className="text-white/68">{label}</span><span className="ml-auto text-xs text-white/35">{ready?"Ready":"Action needed"}</span></div>}
function formatDate(value:string){return new Date(value).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"})+" UTC"}
