export type LegalSection = { heading: string; paragraphs?: string[]; items?: string[] };
export type LegalDocument = { slug: string; shortTitle: string; title: string; summary: string; sections: LegalSection[] };

export const legalDocuments: LegalDocument[] = [
  {
    slug: "terms-of-service", shortTitle: "Terms of Service", title: "Nexora Rank Terms of Service",
    summary: "The service agreement for Nexora Rank accounts, workspaces, integrations, automations, and private-beta plans.",
    sections: [
      { heading: "1. Status and acceptance", paragraphs: ["Effective August 28, 2026. Nexora Rank is a private-beta service. By creating an account or using the website, dashboard, bot, API, integrations, or a workspace, you agree to these Terms and the policies in the Legal Center. If you act for a community or organization, you confirm that you may bind it to these terms."] },
      { heading: "2. Eligibility and accounts", paragraphs: ["You must be at least 13, meet the minimum age for Discord and Roblox in your location, and have any parent or guardian permission required by law. Information must be accurate and sign-in methods must be protected."], items: ["Connect only Discord and Roblox accounts you may use.", "Workspace owners must be authorized to manage each connected server, group, community, or experience.", "Never share passwords, Discord user tokens, Roblox security cookies, API keys, or OAuth client secrets.", "Report suspected unauthorized access promptly."] },
      { heading: "3. Free-plan Roblox community requirement", paragraphs: ["When membership enforcement is enabled, the owner of every Free workspace must connect their Roblox identity and remain a member of the Nexora Roblox community with ID 596263047. Nexora verifies this automatically. Workspaces on an active paid or trial plan above Free are exempt."], items: ["A confirmed departure starts a 48-hour grace period.", "Rejoining during the grace period restores eligibility.", "If the owner remains absent after the deadline, suspension may occur on the next successful automated verification.", "Roblox outages and inconclusive checks do not start the timer or cause a new suspension.", "Rejoining, or becoming eligible for an exempt active plan, automatically restores a workspace suspended only for this rule."] },
      { heading: "4. Workspace responsibility", paragraphs: ["Rank changes, role sync, applications, activity records, API requests, and automations can affect real communities. Owners control staff access and must review permissions, rank paths, connected resources, API keys, and automation rules. A workspace ID is permanent; a 25-character API key can be replaced, immediately disabling its predecessor. Nexora may retain audit evidence needed for security and dispute handling."] },
      { heading: "5. Beta availability", paragraphs: ["Features may change, pause, or be removed during beta. Nexora does not guarantee uninterrupted service or that Discord, Roblox, Vercel, Supabase, or another platform will accept every request. The Status page reports current health where available. Operations may be limited to protect users, platforms, or reliability."] },
      { heading: "6. Plans, donations, and billing", paragraphs: ["The private beta currently offers a Free plan without active checkout. Optional support through the linked Roblox catalog item or Ko-fi is a donation, is not a subscription, and does not buy plan access, preferential enforcement, ownership, or guaranteed development. Third-party platform terms apply. Before paid plans launch, Nexora will show price, tax handling, renewal, cancellation, refund terms, provider, and material limits before purchase. A downgrade to Free may make the Roblox requirement applicable after notice and a reasonable opportunity to comply."] },
      { heading: "7. Suspension and termination", paragraphs: ["Nexora may restrict or end access for material or repeated policy violations, abuse, security risks, unlawful use, third-party platform enforcement, future non-payment, or failure to meet a plan eligibility rule. Where appropriate, Nexora will explain the reason and offer a review path. Deletion requests remain subject to necessary security, legal, dispute, audit, and backup retention."] },
      { heading: "8. Intellectual property", paragraphs: ["Nexora Rank and its original code, interface, graphics, and brand are protected by applicable law. You retain submitted content and grant Nexora a limited worldwide license to host, process, transmit, and display it only to provide, secure, and support the service. Feedback may be used without payment or public attribution."] },
      { heading: "9. Disclaimers and liability", paragraphs: ["The beta is provided on an as-available basis. To the maximum extent permitted by law, Nexora disclaims implied warranties and is not responsible for events controlled by independent platforms. Nothing excludes mandatory consumer rights or liability that cannot legally be limited. Operator identity, governing law, disputes, and final liability terms require qualified legal review before public billing."] },
      { heading: "10. Changes and contact", paragraphs: ["Material changes will be dated and announced through the dashboard or official support community when appropriate. Urgent security, legal, or platform changes may take effect sooner. The legal operator and dedicated legal, privacy, and support contacts will be published before public billing; never post secrets or personal data publicly."] },
    ],
  },
  {
    slug: "terms-of-use", shortTitle: "Terms of Use", title: "Website & Platform Terms of Use",
    summary: "Rules for Nexora’s website, dashboard, connected platform, API access, and public material.",
    sections: [
      { heading: "1. Scope", paragraphs: ["Effective August 28, 2026. These rules apply to Nexora’s public website, dashboard, integrations, API access, status page, and public material. Account and workspace use is also governed by the Terms of Service."] },
      { heading: "2. Permitted use", items: ["Evaluate or operate Nexora for a community you own or may manage.", "Use Nexora only in authorized servers, groups, experiences, and workspaces.", "Link to public pages without implying sponsorship or partnership."] },
      { heading: "3. Prohibited use", items: ["Probe, scrape, overload, reverse engineer, or bypass security, rate limits, or suspension controls except where law expressly permits.", "Impersonate anyone or misrepresent affiliation or completed actions.", "Create a confusingly similar service using Nexora’s interface or brand.", "Submit malware, unlawful content, stolen credentials, unauthorized personal data, or another person’s secrets.", "Manipulate identities, plan status, Roblox membership checks, eligibility, or audit evidence.", "Spam, raid, harass, exploit, discriminate, defraud, or evade Discord or Roblox enforcement."] },
      { heading: "4. Independent platforms", paragraphs: ["Discord and Roblox are independent platforms with their own terms, developer policies, community standards, privacy practices, permissions, and limits. Nexora is not endorsed by or affiliated with Discord Inc. or Roblox Corporation unless explicitly stated."] },
      { heading: "5. Automated controls", paragraphs: ["Nexora uses automated controls for security, quotas, plan eligibility, and the Free-plan Roblox community rule. Provider failures are inconclusive rather than non-compliant. Owners may request review of an incorrect automated result through official support."] },
      { heading: "6. Availability", paragraphs: ["Beta features and limits may change. Status history begins when measurements are stored; an unknown day is not a representation of uptime or downtime. The Status page is operational information, not a service-level agreement. Continued use after an effective update means acceptance where permitted by law."] },
    ],
  },
  {
    slug: "privacy", shortTitle: "Privacy Policy", title: "Nexora Rank Privacy Policy",
    summary: "What Nexora processes, why it is needed, how automated eligibility works, and the choices available to users.",
    sections: [
      { heading: "1. Scope", paragraphs: ["Effective August 28, 2026. This policy covers the Nexora private beta: website, sign-in, onboarding, dashboard, Discord bot, Roblox integration, API, status page, support, and workspaces. Nexora is not intended for children under 13. The legal operator and dedicated privacy contact will be added before public billing."] },
      { heading: "2. Data processed", items: ["Account data: Supabase user ID, contact email, name, avatar, session, and authentication metadata.", "Discord data: account ID, username, display name, avatar, connected server ID, authorized roles, membership, and integration status.", "Roblox data: account ID, username, display name, avatar, communities visible to the connected account, the community selected during onboarding, public community membership and role, and authorized results.", "Workspace data: permanent workspace ID, members, roles, plan, configuration, applications, activity, rank actions, automations, API key hash and prefix, API use, and audit records. The full API key is shown once and is not stored in readable form.", "Eligibility data: membership in Roblox community 596263047, check times, grace dates, provider errors, and membership-policy suspension status.", "Technical data: timestamps, request status, browser/device and approximate network information, security events, logs, and daily service-health snapshots.", "Future billing data: customer, plan, invoice, renewal, and payment-status identifiers; Nexora does not intend to store full card details."] },
      { heading: "3. Sources", paragraphs: ["Data comes from you, authorized workspace users, Supabase Auth, Discord OAuth and APIs, Roblox OAuth and public or authorized APIs, connected game servers, Nexora security systems, and future billing providers. Roblox’s public membership endpoint may be checked without retaining a Roblox access token for that check."] },
      { heading: "4. Purposes and legal bases", paragraphs: ["Nexora processes data to create accounts and workspaces, provide integrations and automations, enforce limits and eligibility, secure and troubleshoot the service, prevent abuse, provide support, maintain auditability, and meet legal obligations. Depending on location and activity, the basis may be contract, legitimate interests, consent, or legal obligation."] },
      { heading: "5. Automated Free-plan eligibility", paragraphs: ["When enabled, Nexora compares the linked Roblox user ID of a Free workspace owner with public membership data for community 596263047. Confirmed absence starts a 48-hour grace period; a successful check after expiry can suspend the workspace. Provider errors do not start the timer or cause new suspension. Rejoining or becoming an eligible active paid or trial workspace restores a workspace suspended only for this rule. Owners may request human review."] },
      { heading: "6. Sharing", paragraphs: ["Data is shared only as needed with infrastructure, authentication, monitoring, support, and future billing providers; with Discord or Roblox for requested functions; when legally required; or to protect users and the service. Nexora does not sell personal data or use Discord or Roblox API data to train general-purpose AI models."] },
      { heading: "7. Retention", paragraphs: ["Account and workspace data is retained while needed for service. Eligibility results and grace dates remain while the workspace exists and may remain in audit records for security or disputes. OAuth data is refreshed or deleted when no longer needed under provider rules. Security records may be kept longer where necessary; deleted data can remain temporarily in encrypted backups."] },
      { heading: "8. Rights and choices", items: ["Disconnect or revoke Discord and Roblox access, understanding required features may stop.", "Request access, correction, deletion, restriction, objection, or portability where applicable.", "Withdraw consent where it is the basis, without affecting earlier lawful processing.", "Request human review of an automated eligibility or suspension result.", "Request workspace deletion subject to necessary security, legal, audit, and backup retention.", "Complain to the relevant data-protection authority."] },
      { heading: "9. Security and transfers", paragraphs: ["Nexora uses scoped OAuth, encrypted transport, row-level database controls, isolated secrets, and audit records. No internet service is perfectly secure. Vercel and Supabase may process data in locations covered by their terms; appropriate transfer safeguards will be used where required."] },
      { heading: "10. Contact and changes", paragraphs: ["Use official Nexora support for beta privacy requests and avoid posting personal data publicly. A dedicated privacy contact and operator identity will be published before public billing. Material changes will be dated and communicated where required."] },
    ],
  },
  {
    slug: "cookies", shortTitle: "Cookie Policy", title: "Cookie & Local Storage Policy",
    summary: "Authentication, security, preference, and optional analytics storage used by Nexora.",
    sections: [
      { heading: "1. Current use", paragraphs: ["Effective August 28, 2026. Nexora uses necessary browser storage for Supabase sessions, OAuth completion, request security, routing, and interface state. Nexora does not currently use advertising cookies."] },
      { heading: "2. Necessary storage", items: ["Authentication cookies that keep a valid session.", "Short-lived OAuth state and verifier values for Discord and Roblox.", "Security, anti-abuse, routing, and request-integrity values used by Nexora, Vercel, or Supabase.", "Local preferences for interface or consent choices."] },
      { heading: "3. Optional storage", paragraphs: ["Optional analytics and other non-essential storage remain off unless configured with an appropriate legal basis and consent where required. Nexora will not silently add advertising or cross-site tracking."] },
      { heading: "4. Controls", paragraphs: ["You may clear or block browser storage, but blocking necessary values may prevent sign-in, OAuth, onboarding, or dashboard use. A consent control will be added before non-essential cookies requiring consent are enabled."] },
    ],
  },
  {
    slug: "acceptable-use", shortTitle: "Acceptable Use", title: "Acceptable Use Policy",
    summary: "Safety, platform-integrity, credential, automation, and eligibility rules for every Nexora surface.",
    sections: [
      { heading: "Use Nexora responsibly", items: ["Do not harass, exploit, discriminate against, threaten, or endanger users.", "Do not automate spam, raids, deceptive engagement, or abusive rank actions.", "Do not evade Discord or Roblox enforcement, permissions, rate limits, or platform rules.", "Do not request, store, or share Discord user tokens, Roblox security cookies, passwords, keys, or another person’s OAuth secrets.", "Do not falsify activity, applications, votes, identities, plan status, Roblox membership, eligibility checks, or audit evidence.", "Do not access another workspace, account, server, group, or experience without authorization.", "Do not sell, broker, profile, or use platform data for general-purpose AI training.", "Do not use Nexora for malware, fraud, unlawful commerce, infringement, or suspension circumvention."] },
      { heading: "Enforcement", paragraphs: ["Nexora may rate-limit, block, reverse, suspend, preserve evidence of, or report abuse. Serious or repeated violations may end access. The Free-plan membership process has its own 48-hour rejoin period and does not limit urgent security, abuse, or legal action."] },
      { heading: "Reporting and review", paragraphs: ["Use official Nexora support to report abuse, security issues, or an incorrect eligibility result. Never post secrets or personal data publicly. Nexora may request information reasonably needed to verify ownership and investigate."] },
    ],
  },
  {
    slug: "refunds", shortTitle: "Refund Policy", title: "Cancellation & Refund Policy",
    summary: "What applies in the free private beta and what must be published before checkout launches.",
    sections: [
      { heading: "No paid checkout today", paragraphs: ["Effective August 28, 2026. Nexora is free in private beta. There is no active checkout, so Nexora cannot charge, cancel, or refund a payment through this site today."] },
      { heading: "Before billing launches", paragraphs: ["Future checkout will identify the seller or merchant of record, total price, taxes, billing period, renewal, cancellation, refund eligibility, and provider terms before payment. Mandatory consumer rights apply regardless of this policy."] },
      { heading: "Planned controls", items: ["Cancel future renewal through a billing portal.", "Keep access through the paid period unless security, abuse, law, or payment failure requires restriction.", "Request review of duplicate, incorrect, or unauthorized charges.", "Receive receipts and visible plan status.", "Receive practical notice before a downgrade makes Free-plan eligibility applicable."] },
      { heading: "Payment provider", paragraphs: ["Lemon Squeezy is under consideration as merchant of record but is not connected. This page will be updated if a provider is selected."] },
    ],
  },
  {
    slug: "subprocessors", shortTitle: "Subprocessors", title: "Infrastructure & Subprocessors",
    summary: "Services used for hosting, authentication, database operations, and independent platform integrations.",
    sections: [
      { heading: "Current infrastructure", items: ["Vercel — hosting, server functions, deployment, delivery, and scheduled membership-check triggers.", "Supabase — authentication, PostgreSQL database, row-level access control, OAuth provider connection, and backend services."] },
      { heading: "Independent platforms", paragraphs: ["Discord and Roblox are integrations and independent platforms, not ordinary Nexora subprocessors. Their terms and privacy policies govern their processing. Nexora contacts them only for sign-in, authorized functions, service health, and the Free-plan membership check."] },
      { heading: "Future provider", items: ["Lemon Squeezy — under consideration for merchant-of-record checkout, taxes, billing, and refunds; not connected."] },
      { heading: "Transfers and changes", paragraphs: ["Provider access is limited to its service. Provider terms govern locations, retention, and security; Nexora will use required transfer safeguards. Material additions will be listed before or promptly after they begin, with notice where required."] },
    ],
  },
];

export function getLegalDocument(slug: string) { return legalDocuments.find((document) => document.slug === slug); }
