"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import {
  Activity, AlertTriangle, ArrowLeft, ArrowRight, ArrowUpRight,
  BarChart3, Bell, Blocks, Bot, Check, ChevronDown, ChevronRight,
  CircleDot, Clock3, Command, Copy, FileCheck2, Filter, Fingerprint, Gamepad2, Gauge, GitBranch,
  History, Home, Inbox, KeyRound, LayoutDashboard, ListFilter,
  MessageSquare, MoreHorizontal, Pause, Play, Plus, Radio, RefreshCcw, Search,
  Settings, Shield, ShieldCheck, Sparkles, SquareArrowOutUpRight,
  Terminal, UserCheck, UsersRound, Webhook, X, Zap,
} from "lucide-react";
import { toast } from "sonner";
import { BrandMark } from "@/components/brand-mark";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";
import {
  Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader,
  DialogTitle, DialogTrigger,
} from "@/components/ui/dialog";
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel,
  DropdownMenuSeparator, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent,
  SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton,
  SidebarMenuItem, SidebarProvider, SidebarTrigger,
} from "@/components/ui/sidebar";

type View = "overview" | "launch" | "members" | "ranking" | "activity" | "applications" | "automations" | "integrations" | "audit" | "settings";

const nav: { id: View; label: string; icon: LucideIcon; badge?: string }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "launch", label: "Launch center", icon: Sparkles, badge: "New" },
  { id: "members", label: "Members", icon: UsersRound },
  { id: "ranking", label: "Rank operations", icon: GitBranch },
  { id: "activity", label: "Activity", icon: Activity },
  { id: "applications", label: "Applications", icon: FileCheck2, badge: "6" },
  { id: "automations", label: "Automations", icon: Blocks },
  { id: "integrations", label: "Integrations", icon: Webhook },
  { id: "audit", label: "Audit log", icon: History },
];

const members = [
  { name: "MiraPlays", display: "Mira", rank: "Senior Barista", discord: "mira.p", activity: "18h 24m", status: "Online", initials: "MP", score: 96 },
  { name: "NexusVee", display: "Nexus", rank: "Shift Leader", discord: "nexusvee", activity: "15h 08m", status: "In game", initials: "NV", score: 92 },
  { name: "KoriOnline", display: "Kori", rank: "Barista", discord: "kori.online", activity: "11h 37m", status: "Offline", initials: "KO", score: 81 },
  { name: "LumaClouds", display: "Luma", rank: "Trainee", discord: "luma.c", activity: "7h 12m", status: "Online", initials: "LC", score: 74 },
  { name: "AxelBuilder", display: "Axel", rank: "Staff Assistant", discord: "axelbuilds", activity: "6h 48m", status: "Offline", initials: "AB", score: 68 },
];

const operations = [
  { user: "MiraPlays", actor: "Dusan", action: "Promoted", detail: "Barista → Senior Barista", time: "12 seconds ago", tone: "success" },
  { user: "NexusVee", actor: "Automation", action: "Session completed", detail: "1h 42m in Main Store", time: "3 minutes ago", tone: "info" },
  { user: "KoriOnline", actor: "Avery", action: "Application approved", detail: "Staff Assistant application", time: "18 minutes ago", tone: "success" },
  { user: "LumaClouds", actor: "Policy engine", action: "Promotion held", detail: "Activity requirement: 82% complete", time: "41 minutes ago", tone: "warning" },
  { user: "AxelBuilder", actor: "Dusan", action: "Note added", detail: "Great performance during rush", time: "1 hour ago", tone: "neutral" },
];

const applications = [
  { name: "JamieBlox", role: "Staff Assistant", score: 92, submitted: "8m ago", stage: "Ready for review", initials: "JB" },
  { name: "PixelRina", role: "Staff Assistant", score: 86, submitted: "24m ago", stage: "Ready for review", initials: "PR" },
  { name: "RobbyDev", role: "Security", score: 78, submitted: "1h ago", stage: "Needs discussion", initials: "RD" },
  { name: "SkylerMint", role: "Staff Assistant", score: 74, submitted: "3h ago", stage: "Ready for review", initials: "SM" },
];

const viewCopy: Record<View, { title: string; description: string }> = {
  overview: { title: "Good afternoon, Dusan", description: "Your workspace is healthy. Here’s what changed today." },
  launch: { title: "Launch center", description: "Connect the stack in the right order and see exactly what is ready." },
  members: { title: "Members", description: "Search staff, inspect readiness, and manage ranks safely." },
  ranking: { title: "Rank operations", description: "Control rank paths, policies, and every requested change." },
  activity: { title: "Activity intelligence", description: "Understand sessions, quotas, and contribution without spreadsheets." },
  applications: { title: "Applications", description: "Move applicants from submission to decision in one flow." },
  automations: { title: "Automations", description: "Turn reliable community rules into safe, repeatable workflows." },
  integrations: { title: "Integrations", description: "Connect Nexora Rank to the tools that run your community." },
  audit: { title: "Audit log", description: "A complete, searchable record of every privileged operation." },
  settings: { title: "Workspace settings", description: "Configure identity, permissions, notifications, and safety." },
};

export default function DashboardPage() {
  const [view, setView] = useState<View>("overview");
  const [search, setSearch] = useState("");
  const copy = viewCopy[view];

  return (
    <SidebarProvider>
      <div className="dashboard-root">
        <Sidebar collapsible="icon" className="border-white/[.065] bg-[#09090d]">
          <SidebarHeader className="px-3 py-3">
            <div className="flex h-11 items-center gap-2.5 overflow-hidden px-1"><BrandMark compact /><div className="min-w-0 group-data-[collapsible=icon]:hidden"><p className="truncate text-sm font-semibold text-white">Nexora Rank</p><p className="truncate text-[10px] text-white/30">Demo workspace</p></div></div>
            <DropdownMenu><DropdownMenuTrigger asChild><button className="workspace-switcher group-data-[collapsible=icon]:hidden"><span className="flex size-7 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500 to-blue-500 text-[10px] font-bold text-white">BC</span><span className="min-w-0 flex-1 text-left"><b>Brew & Co.</b><small>Roblox community</small></span><ChevronDown className="size-3.5 text-white/28" /></button></DropdownMenuTrigger><DropdownMenuContent className="w-60 border-white/10 bg-[#141419]"><DropdownMenuLabel>Workspaces</DropdownMenuLabel><DropdownMenuItem><Check className="text-violet-300" /> Brew & Co.</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => toast.info("Workspace creation is part of the next backend milestone.")}><Plus /> Create workspace</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
          </SidebarHeader>
          <SidebarContent className="px-2">
            <SidebarGroup><SidebarGroupLabel>Operate</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.slice(0, 7).map((item) => <NavItem key={item.id} item={item} active={view === item.id} onSelect={() => setView(item.id)} />)}</SidebarMenu></SidebarGroupContent></SidebarGroup>
            <SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.slice(7).map((item) => <NavItem key={item.id} item={item} active={view === item.id} onSelect={() => setView(item.id)} />)}<NavItem item={{ id: "settings", label: "Settings", icon: Settings }} active={view === "settings"} onSelect={() => setView("settings")} /></SidebarMenu></SidebarGroupContent></SidebarGroup>
          </SidebarContent>
          <SidebarFooter className="p-3"><div className="system-status group-data-[collapsible=icon]:hidden"><div className="flex items-center justify-between"><span className="flex items-center gap-2"><i /> Systems ready</span><span>Preview</span></div><p>External sync is paused until OAuth launches.</p></div><Link href="/" className="flex h-9 items-center gap-2 rounded-lg px-2 text-xs text-white/36 hover:bg-white/[.04] hover:text-white"><Home className="size-4" /><span className="group-data-[collapsible=icon]:hidden">Back to website</span></Link></SidebarFooter>
        </Sidebar>

        <SidebarInset className="min-w-0 bg-[#09090d]">
          <header className="dashboard-topbar">
            <div className="flex min-w-0 items-center gap-3"><SidebarTrigger className="text-white/45 hover:bg-white/[.05] hover:text-white" /><div className="h-5 w-px bg-white/[.07]" /><div className="hidden min-w-0 items-center gap-2 text-xs text-white/28 sm:flex"><span>Brew & Co.</span><ChevronRight className="size-3" /><span className="truncate text-white/55">{copy.title}</span></div></div>
            <div className="flex items-center gap-2">
              <button className="command-search hidden sm:flex" onClick={() => { setView("members"); setSearch(""); }}><Search className="size-3.5" /><span>Search workspace</span><kbd><Command className="size-2.5" /> K</kbd></button>
              <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" className="relative text-white/48 hover:bg-white/[.06] hover:text-white"><Bell /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-violet-400 ring-2 ring-[#09090d]" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-80 border-white/10 bg-[#141419] p-2"><DropdownMenuLabel>Notifications</DropdownMenuLabel><Notification title="Application queue" text="6 submissions are ready for review." /><Notification title="Activity milestone" text="Your team passed 300 hours this month." /></DropdownMenuContent></DropdownMenu>
              <DropdownMenu><DropdownMenuTrigger asChild><button className="user-avatar">DP</button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52 border-white/10 bg-[#141419]"><DropdownMenuLabel><span className="block">Dusan</span><span className="text-[10px] font-normal text-white/30">Workspace owner</span></DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onClick={() => setView("settings")}><Settings /> Settings</DropdownMenuItem><DropdownMenuItem asChild><Link href="/"><ArrowLeft /> Exit demo</Link></DropdownMenuItem></DropdownMenuContent></DropdownMenu>
            </div>
          </header>

          <div className="dashboard-content">
            <div className="page-heading"><div><h1>{copy.title}</h1><p>{copy.description}</p></div><div className="flex items-center gap-2"><span className="preview-badge"><Sparkles className="size-3" /> Interactive preview</span>{(view === "members" || view === "ranking") && <RankDialog trigger={<Button className="button-glow rounded-xl"><GitBranch /> New rank action</Button>} />}{view === "applications" && <Button className="button-glow rounded-xl" onClick={() => toast.success("New form draft created in the preview.")}><Plus /> New form</Button>}{view === "automations" && <Button className="button-glow rounded-xl" onClick={() => toast.success("Automation draft created.")}><Plus /> New automation</Button>}</div></div>
            {view === "overview" && <Overview onNavigate={setView} />}
            {view === "launch" && <LaunchCenter onNavigate={setView} />}
            {view === "members" && <Members search={search} setSearch={setSearch} />}
            {view === "ranking" && <Ranking />}
            {view === "activity" && <ActivityView />}
            {view === "applications" && <ApplicationsView />}
            {view === "automations" && <AutomationsView />}
            {view === "integrations" && <IntegrationsView />}
            {view === "audit" && <AuditView />}
            {view === "settings" && <SettingsView />}
          </div>
        </SidebarInset>
        <Toaster richColors position="bottom-right" />
      </div>
    </SidebarProvider>
  );
}

function NavItem({ item, active, onSelect }: { item: { id: View; label: string; icon: LucideIcon; badge?: string }; active: boolean; onSelect: () => void }) {
  const Icon = item.icon;
  return <SidebarMenuItem><SidebarMenuButton onClick={onSelect} isActive={active} tooltip={item.label} className="h-9 text-white/45 data-[active=true]:bg-violet-400/[.10] data-[active=true]:text-violet-200 hover:bg-white/[.04] hover:text-white"><Icon /><span>{item.label}</span>{item.badge && <span className="ml-auto rounded-full bg-violet-400/15 px-1.5 py-0.5 text-[9px] text-violet-200">{item.badge}</span>}</SidebarMenuButton></SidebarMenuItem>;
}

function Notification({ title, text }: { title: string; text: string }) { return <div className="rounded-lg p-2.5 hover:bg-white/[.04]"><p className="text-xs font-medium text-white/75">{title}</p><p className="mt-1 text-[11px] leading-5 text-white/32">{text}</p></div>; }

function Overview({ onNavigate }: { onNavigate: (view: View) => void }) {
  return <div className="space-y-5"><div className="metrics-grid"><Metric title="Active staff" value="42" change="12.4%" icon={UsersRound} color="violet" /><Metric title="Rank actions" value="187" change="24.1%" icon={GitBranch} color="blue" /><Metric title="Hours tracked" value="328" change="8.3%" icon={Clock3} color="cyan" /><Metric title="Open applications" value="6" change="2 new" icon={FileCheck2} color="pink" /></div><div className="grid gap-5 xl:grid-cols-[1.45fr_.85fr]"><ActivityChart /><QuickActions onNavigate={onNavigate} /></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><OperationsTable compact /><Readiness onNavigate={onNavigate} /></div></div>;
}

function LaunchCenter({ onNavigate }: { onNavigate: (view: View) => void }) {
  const setup = [
    { title: "Product workspace", detail: "Workspace model, roles, and audit foundation", state: "Complete", icon: LayoutDashboard, done: true },
    { title: "Secure database", detail: "16 tables, row security, idempotent webhooks", state: "Prepared", icon: ShieldCheck, done: true },
    { title: "Discord authorization", detail: "OAuth callback and secure session exchange", state: "Ready to connect", icon: Bot },
    { title: "Discord bot", detail: "Identity, commands, permissions, and profile", state: "Design ready", icon: Command },
    { title: "Roblox Open Cloud", detail: "Group permissions, rank bindings, activity SDK", state: "Next", icon: Gamepad2 },
    { title: "Production launch", detail: "End-to-end sync tests, monitoring, invite rollout", state: "Locked", icon: Radio },
  ];

  return <div className="space-y-5"><section className="launch-hero"><div><p><Sparkles /> Guided setup</p><h2>From empty workspace to verified operation.</h2><span>Nexora shows what is configured, what is waiting on an external account, and what must be tested before launch.</span></div><div className="launch-score"><b>2</b><span>of 6 ready</span></div></section><section className="launch-rail"><span><Fingerprint /> Identity</span><ChevronRight /><span><ShieldCheck /> Policy</span><ChevronRight /><span><Zap /> Action</span><ChevronRight /><span><History /> Evidence</span></section><div className="launch-grid">{setup.map(({ title, detail, state, icon: Icon, done }, index) => <article className={`launch-card ${done ? "done" : ""}`} key={title}><div className="flex items-start justify-between"><span className="launch-icon"><Icon /></span><span className="launch-index">0{index + 1}</span></div><h3>{title}</h3><p>{detail}</p><div className="mt-6 flex items-center justify-between border-t border-white/[.055] pt-4"><span className="launch-state">{done ? <Check /> : <CircleDot />}{state}</span>{!done && index < 5 && <button onClick={() => index === 2 ? onNavigate("integrations") : toast.info(`${title} setup will unlock in this guided flow.`)}>Configure <ArrowRight /></button>}</div></article>)}</div><div className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><article className="dash-card"><CardHeader title="External connections" description="Nothing sensitive is placed in the browser or audit metadata" /><div className="mt-5 grid gap-3 sm:grid-cols-2"><button className="dev-tool" onClick={() => onNavigate("integrations")}><Bot /><span><b>Connect Discord</b><small>OAuth, guild, commands, and role mapping</small></span><ArrowRight /></button><button className="dev-tool" onClick={() => onNavigate("integrations")}><Gamepad2 /><span><b>Connect Roblox</b><small>Open Cloud key, group, ranks, and activity</small></span><ArrowRight /></button></div></article><article className="dash-card"><CardHeader title="Bot identity" description="New monochrome profile and command surface" /><Link href="/bot" className="mt-5 flex min-h-20 items-center gap-4 rounded-xl border border-white/[.07] bg-white/[.02] p-4 transition hover:bg-white/[.04]"><BrandMark /><span className="min-w-0 flex-1"><b className="block text-xs text-white/68">Meet Nexora for Discord</b><small className="mt-1 block text-[9px] text-white/25">Logo, description, commands, permissions</small></span><SquareArrowOutUpRight className="size-4 text-white/25" /></Link></article></div></div>;
}

function Metric({ title, value, change, icon: Icon, color }: { title: string; value: string; change: string; icon: LucideIcon; color: string }) { return <article className="metric-card"><div className={`metric-icon ${color}`}><Icon /></div><div className="mt-6 flex items-end justify-between"><div><p>{title}</p><h3>{value}</h3></div><span><ArrowUpRight /> {change}</span></div></article>; }

function ActivityChart() { return <article className="dash-card"><CardHeader title="Activity pulse" description="Staff hours across all connected experiences" action={<button className="period-select">Last 7 days <ChevronDown /></button>} /><div className="mt-6 h-64"><svg className="h-full w-full overflow-visible" viewBox="0 0 700 250" preserveAspectRatio="none" aria-label="Weekly staff activity chart"><defs><linearGradient id="dash-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#8b5cf6" stopOpacity=".32"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs>{[35,90,145,200].map(y => <line key={y} x1="0" x2="700" y1={y} y2={y} stroke="rgba(255,255,255,.05)" />)}<path d="M0 211 C48 198 74 171 116 182 S182 198 226 144 S298 165 343 124 S417 151 460 96 S535 123 578 72 S650 79 700 39 L700 250H0Z" fill="url(#dash-area)"/><path d="M0 211 C48 198 74 171 116 182 S182 198 226 144 S298 165 343 124 S417 151 460 96 S535 123 578 72 S650 79 700 39" fill="none" stroke="#9f7aea" strokeWidth="3" vectorEffect="non-scaling-stroke"/><circle cx="700" cy="39" r="5" fill="#c4b5fd" stroke="#17111f" strokeWidth="4" vectorEffect="non-scaling-stroke"/></svg></div><div className="mt-2 grid grid-cols-7 text-center text-[10px] text-white/22">{["Thu","Fri","Sat","Sun","Mon","Tue","Wed"].map(d => <span key={d}>{d}</span>)}</div></article>; }

function QuickActions({ onNavigate }: { onNavigate: (view: View) => void }) { const actions = [{ icon: GitBranch, label: "Rank member", view: "ranking" as View },{ icon: UserCheck, label: "Review applications", view: "applications" as View },{ icon: Blocks, label: "Build automation", view: "automations" as View },{ icon: History, label: "Open audit log", view: "audit" as View }]; return <article className="dash-card"><CardHeader title="Quick actions" description="Start a common operation" /><div className="mt-5 grid grid-cols-2 gap-3">{actions.map(({ icon: Icon, label, view }) => <button key={label} className="quick-action" onClick={() => onNavigate(view)}><span><Icon /></span><b>{label}</b><ArrowRight className="arrow" /></button>)}</div><div className="mt-5 rounded-xl border border-violet-400/10 bg-violet-400/[.045] p-3"><div className="flex items-center gap-2 text-xs font-medium text-violet-200"><ShieldCheck className="size-4" /> Safety preview enabled</div><p className="mt-1.5 text-[10px] leading-5 text-white/28">Actions are simulated until your Roblox group and Discord server are connected.</p></div></article>; }

function Readiness({ onNavigate }: { onNavigate: (view: View) => void }) { return <article className="dash-card"><CardHeader title="Workspace readiness" description="Launch checklist" /><div className="mt-5 flex items-center gap-5"><div className="readiness-ring"><b>68%</b><span>ready</span></div><div className="min-w-0 flex-1 space-y-3"><ReadyRow done label="Create workspace" /><ReadyRow done label="Configure rank paths" /><ReadyRow label="Connect Discord" /><ReadyRow label="Connect Roblox Open Cloud" /></div></div><Button variant="outline" className="mt-5 w-full border-white/10 bg-white/[.02] text-white/62 hover:bg-white/[.05] hover:text-white" onClick={() => onNavigate("launch")}>Open launch center <ArrowRight /></Button></article>; }
function ReadyRow({ done = false, label }: { done?: boolean; label: string }) { return <div className="flex items-center gap-2 text-xs"><span className={`flex size-5 items-center justify-center rounded-full ${done ? "bg-emerald-400/10 text-emerald-400" : "bg-white/[.04] text-white/18"}`}>{done ? <Check className="size-3" /> : <CircleDot className="size-3" />}</span><span className={done ? "text-white/58" : "text-white/28"}>{label}</span></div>; }

function Members({ search, setSearch }: { search: string; setSearch: (value: string) => void }) { const filtered = useMemo(() => members.filter(m => `${m.name} ${m.rank} ${m.discord}`.toLowerCase().includes(search.toLowerCase())), [search]); return <div className="space-y-5"><div className="table-toolbar"><label className="table-search"><Search /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search username, Discord, or rank…" /></label><div className="flex gap-2"><Button variant="outline" className="border-white/10 bg-white/[.02] text-white/52"><Filter /> Filters</Button><Button variant="outline" className="border-white/10 bg-white/[.02] text-white/52" onClick={() => toast.success("Member list refreshed.")}><RefreshCcw /> Sync</Button></div></div><div className="data-table-card"><div className="member-table-head"><span>Member</span><span>Current rank</span><span>Activity (30d)</span><span>Readiness</span><span>Status</span><span /></div>{filtered.map(member => <div className="member-table-row" key={member.name}><div className="member-identity"><Avatar initials={member.initials} /><div><b>{member.name}</b><span>@{member.discord}</span></div></div><span className="rank-pill">{member.rank}</span><div><b className="block text-xs font-medium text-white/64">{member.activity}</b><span className="text-[10px] text-white/25">last 30 days</span></div><div className="w-28"><div className="flex justify-between text-[10px]"><span className="text-white/28">Score</span><span className="text-white/55">{member.score}%</span></div><Progress value={member.score} className="mt-2 h-1 bg-white/[.06] [&>div]:bg-violet-400" /></div><Status label={member.status} /><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" variant="ghost" className="text-white/32 hover:bg-white/[.05] hover:text-white"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="border-white/10 bg-[#141419]"><DropdownMenuItem onClick={() => toast.info(`Opened ${member.name}'s profile preview.`)}><SquareArrowOutUpRight /> View profile</DropdownMenuItem><DropdownMenuItem onClick={() => toast.success(`Note draft opened for ${member.name}.`)}><MessageSquare /> Add note</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => toast.info("Use New rank action to preview a safe rank change.")}><GitBranch /> Change rank</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}{filtered.length === 0 && <div className="py-16 text-center"><Search className="mx-auto size-6 text-white/15" /><p className="mt-3 text-sm text-white/35">No members match “{search}”</p></div>}</div></div>; }

function Ranking() { return <div className="space-y-5"><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="dash-card"><CardHeader title="Rank paths" description="Allowed promotion and demotion routes" action={<Button variant="ghost" size="sm" className="text-violet-300" onClick={() => toast.success("Rank path draft created.")}><Plus /> Add path</Button>} /><div className="mt-5 space-y-2">{[["Trainee","Barista","4h activity"],["Barista","Senior Barista","12h + approval"],["Senior Barista","Shift Leader","Manual approval"]].map(([from,to,rule],i) => <div key={from} className="rank-path"><span className="path-index">{i+1}</span><div><b>{from}</b><small>From</small></div><ArrowRight /><div><b>{to}</b><small>To</small></div><span className="ml-auto policy-pill"><Shield className="size-3" />{rule}</span></div>)}</div></article><article className="dash-card"><CardHeader title="Safety controls" description="Global ranking guardrails" /><SettingToggle title="Require a reason" description="Every change needs written context" checked /><SettingToggle title="Two-person approval" description="For leadership rank changes" checked /><SettingToggle title="Emergency pause" description="Stop all rank operations" /><div className="mt-5 rounded-xl border border-emerald-400/10 bg-emerald-400/[.04] p-3 text-xs text-emerald-200/70"><ShieldCheck className="mr-2 inline size-4" />No policy conflicts detected.</div></article></div><OperationsTable /></div>; }

function ActivityView() { return <Tabs defaultValue="overview" className="gap-5"><TabsList variant="line" className="border-b border-white/[.06]"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="sessions">Live sessions <span className="ml-1 rounded-full bg-emerald-400/10 px-1.5 text-[9px] text-emerald-300">8</span></TabsTrigger><TabsTrigger value="quotas">Quotas</TabsTrigger></TabsList><TabsContent value="overview"><div className="space-y-5"><div className="metrics-grid"><Metric title="Active now" value="8" change="Live" icon={Radio} color="cyan" /><Metric title="Hours this week" value="94.2" change="14.2%" icon={Clock3} color="violet" /><Metric title="Quota completion" value="82%" change="6.1%" icon={Gauge} color="blue" /><Metric title="Avg. session" value="1h 18m" change="3.8%" icon={BarChart3} color="pink" /></div><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><ActivityChart /><Leaderboard /></div></div></TabsContent><TabsContent value="sessions"><LiveSessions /></TabsContent><TabsContent value="quotas"><QuotaPanel /></TabsContent></Tabs>; }

function Leaderboard() { return <article className="dash-card"><CardHeader title="Top contributors" description="Activity this month" /><div className="mt-4 space-y-1">{members.slice(0,4).map((m,i) => <div className="leader-row" key={m.name}><span className="leader-number">{i+1}</span><Avatar initials={m.initials} /><div className="min-w-0 flex-1"><b>{m.name}</b><span>{m.rank}</span></div><strong>{m.activity}</strong></div>)}</div></article>; }
function LiveSessions() { return <div className="data-table-card p-3 sm:p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{members.slice(0,3).map((m,i) => <article className="live-session" key={m.name}><div className="flex items-center gap-3"><Avatar initials={m.initials} online /><div><b>{m.name}</b><span>Main Store • Server {i+2}</span></div></div><div className="mt-5 flex items-end justify-between"><div><span className="text-[10px] text-white/25">Session duration</span><strong className="block text-xl text-white">{["1:42:08","0:58:44","0:31:12"][i]}</strong></div><span className="live-pill"><Radio /> Live</span></div></article>)}</div></div>; }
function QuotaPanel() { return <div className="grid gap-5 lg:grid-cols-2">{[["Trainees","4 hours weekly",72],["Baristas","8 hours weekly",86],["Senior Baristas","10 hours weekly",91],["Shift Leaders","12 hours weekly",78]].map(([name,target,value]) => <article className="dash-card" key={String(name)}><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold text-white">{name}</h3><p className="mt-1 text-xs text-white/28">{target}</p></div><b className="text-xl text-white">{value}%</b></div><Progress value={Number(value)} className="mt-6 h-2 bg-white/[.06] [&>div]:bg-gradient-to-r [&>div]:from-violet-500 [&>div]:to-blue-400" /><p className="mt-3 text-[10px] text-white/24">Team-wide completion for the current quota period</p></article>)}</div>; }

function ApplicationsView() { return <Tabs defaultValue="queue" className="gap-5"><TabsList variant="line" className="border-b border-white/[.06]"><TabsTrigger value="queue">Review queue</TabsTrigger><TabsTrigger value="forms">Forms</TabsTrigger><TabsTrigger value="analytics">Analytics</TabsTrigger></TabsList><TabsContent value="queue"><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="data-table-card"><div className="p-4 sm:p-5"><CardHeader title="Ready for review" description="Prioritized by score and submission time" /></div>{applications.map(app => <ApplicantRow key={app.name} app={app} />)}</article><ApplicationSummary /></div></TabsContent><TabsContent value="forms"><div className="grid gap-4 md:grid-cols-2">{[["Staff Assistant","Open","128 responses"],["Security Team","Open","46 responses"],["Shift Leader","Private","18 responses"]].map(([name,status,responses]) => <article className="dash-card" key={name}><div className="flex justify-between"><span className="form-icon"><FileCheck2 /></span><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent className="border-white/10 bg-[#141419]"><DropdownMenuItem onClick={() => toast.success("Form editor opened in preview mode.")}>Edit form</DropdownMenuItem><DropdownMenuItem onClick={() => { navigator.clipboard?.writeText("https://nexora.rank/apply/demo"); toast.success("Application link copied."); }}><Copy /> Copy link</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><h3 className="mt-5 text-base font-semibold text-white">{name}</h3><p className="mt-1 text-xs text-white/28">{responses}</p><div className="mt-6 flex items-center justify-between"><Status label={status} /><span className="text-[10px] text-white/22">Updated 2d ago</span></div></article>)}</div></TabsContent><TabsContent value="analytics"><div className="metrics-grid"><Metric title="Submissions" value="192" change="18.2%" icon={Inbox} color="violet" /><Metric title="Approval rate" value="42%" change="3.4%" icon={UserCheck} color="cyan" /><Metric title="Avg. review" value="9h" change="2h faster" icon={Clock3} color="blue" /><Metric title="Auto-flagged" value="7" change="3.6%" icon={Shield} color="pink" /></div></TabsContent></Tabs>; }

function ApplicantRow({ app }: { app: typeof applications[number] }) { return <div className="applicant-row"><Avatar initials={app.initials} /><div className="min-w-0 flex-1"><b>{app.name}</b><span>{app.role} • {app.submitted}</span></div><div className="score-chip"><strong>{app.score}</strong><span>score</span></div><Dialog><DialogTrigger asChild><Button size="sm" variant="outline" className="border-white/10 bg-white/[.02] text-white/60">Review</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#111117] text-white sm:max-w-xl"><DialogHeader><DialogTitle>Review {app.name}</DialogTitle><DialogDescription className="text-white/40">{app.role} application • Automated score {app.score}/100</DialogDescription></DialogHeader><div className="space-y-3 py-2"><ReviewAnswer question="Why do you want to join our staff team?" answer="I enjoy helping new players and I want to make the community more welcoming and organized." /><ReviewAnswer question="How would you handle an upset customer?" answer="I would stay calm, listen first, explain the next step clearly, and ask a leader for help when needed." /></div><DialogFooter><DialogClose asChild><Button variant="outline" className="border-white/10" onClick={() => toast.error(`${app.name}'s application declined in preview.`)}><X /> Decline</Button></DialogClose><DialogClose asChild><Button className="button-glow" onClick={() => toast.success(`${app.name}'s application approved.`)}><Check /> Approve</Button></DialogClose></DialogFooter></DialogContent></Dialog></div>; }
function ReviewAnswer({ question, answer }: { question: string; answer: string }) { return <div className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><p className="text-xs font-medium text-white/70">{question}</p><p className="mt-2 text-xs leading-6 text-white/36">{answer}</p></div>; }
function ApplicationSummary() { return <article className="dash-card"><CardHeader title="Queue health" description="Today’s review performance" /><div className="mt-6 grid grid-cols-3 gap-2"><MiniStat value="6" label="Waiting" /><MiniStat value="9h" label="Avg. age" /><MiniStat value="3" label="Reviewers" /></div><div className="mt-7"><div className="flex justify-between text-xs"><span className="text-white/35">Daily goal</span><span className="text-white/58">14 / 20 reviewed</span></div><Progress value={70} className="mt-2 h-2 bg-white/[.06] [&>div]:bg-violet-400" /></div><div className="mt-7 rounded-xl border border-amber-400/10 bg-amber-400/[.035] p-3"><p className="flex items-center gap-2 text-xs font-medium text-amber-200/70"><AlertTriangle className="size-4" /> One application needs discussion</p><p className="mt-1.5 text-[10px] leading-5 text-white/26">RobbyDev received mixed reviewer signals. No automated decision will be made.</p></div></article>; }

function AutomationsView() { const [enabled, setEnabled] = useState([true,true,false,true]); const data = [{name:"Application approved",desc:"Set Roblox rank and send a welcome DM",runs:"48 runs",icon:FileCheck2},{name:"Quota completed",desc:"Add Discord role and post recognition",runs:"126 runs",icon:Gauge},{name:"Inactivity check",desc:"Flag staff below weekly requirements",runs:"Not run",icon:Activity},{name:"Rank change log",desc:"Post an audit embed to the staff channel",runs:"392 runs",icon:History}]; return <div className="space-y-5"><div className="automation-banner"><div><p><Sparkles /> Automation studio</p><h2>Turn policy into a reliable workflow.</h2><span>Every run is previewable, permission-checked, and written to your audit log.</span></div><div className="hidden items-center gap-2 lg:flex"><FlowPill icon={Zap} text="Trigger" /><ArrowRight /><FlowPill icon={ShieldCheck} text="Check" /><ArrowRight /><FlowPill icon={Play} text="Act" /></div></div><div className="grid gap-4 md:grid-cols-2">{data.map((item,i) => { const Icon=item.icon; return <article className="dash-card automation-card" key={item.name}><div className="flex items-start justify-between"><span className="automation-icon"><Icon /></span><Switch checked={enabled[i]} onCheckedChange={() => { setEnabled(v => v.map((x,j) => j===i ? !x : x)); toast.success(`${item.name} ${enabled[i] ? "paused" : "enabled"}.`); }} aria-label={`Toggle ${item.name}`} /></div><h3>{item.name}</h3><p>{item.desc}</p><div className="mt-6 flex items-center justify-between border-t border-white/[.06] pt-4"><span className="text-[10px] text-white/25">{item.runs} • 0 failures</span><Button variant="ghost" size="sm" className="text-white/42" onClick={() => toast.info("Automation editor opened in preview mode.")}>Edit <ArrowRight /></Button></div></article>})}</div></div>; }
function FlowPill({ icon: Icon, text }: { icon: LucideIcon; text: string }) { return <span className="flow-pill"><Icon />{text}</span>; }

function IntegrationsView() { return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><IntegrationCard icon={Bot} title="Discord" description="Commands, role sync, notifications, and account linking." color="#5865F2" items={["OAuth sign-in","Role bindings","Slash commands","Audit channels"]} /><IntegrationCard icon={Gamepad2} title="Roblox" description="Secure group management through official Open Cloud." color="#ef4444" items={["Group ranks","Membership lookup","Activity SDK","Scoped API key"]} /></div><article className="dash-card"><CardHeader title="Developer tools" description="Connect your own systems to Nexora Rank" /><div className="mt-5 grid gap-3 md:grid-cols-3"><DevTool icon={KeyRound} title="API keys" text="Scoped keys with rotation and usage logs" /><DevTool icon={Webhook} title="Webhooks" text="Signed events with automatic retries" /><DevTool icon={Terminal} title="Roblox SDK" text="Server-side activity and permission checks" /></div></article></div>; }
function IntegrationCard({ icon: Icon, title, description, color, items }: { icon: LucideIcon; title: string; description: string; color: string; items: string[] }) { return <article className="integration-card"><div className="integration-head"><span style={{color,background:`${color}18`}}><Icon /></span><span className="coming-chip">COMING SOON</span></div><h2>{title}</h2><p>{description}</p><ul>{items.map(item => <li key={item}><Check />{item}</li>)}</ul><Button disabled className="mt-7 w-full border border-white/[.07] bg-white/[.03] text-white/30">Connect {title}</Button></article>; }
function DevTool({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <button className="dev-tool" onClick={() => toast.info(`${title} will unlock with the backend API.`)}><Icon /><span><b>{title}</b><small>{text}</small></span><ChevronRight /></button>; }

function AuditView() { const [query,setQuery]=useState(""); const rows=operations.filter(o => `${o.user} ${o.actor} ${o.action} ${o.detail}`.toLowerCase().includes(query.toLowerCase())); return <div className="space-y-5"><div className="table-toolbar"><label className="table-search"><Search /><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actions, actors, or members…" /></label><div className="flex gap-2"><Button variant="outline" className="border-white/10 bg-white/[.02] text-white/52"><ListFilter /> All events</Button><Button variant="outline" className="border-white/10 bg-white/[.02] text-white/52" onClick={() => toast.success("Audit export prepared in preview mode.")}><SquareArrowOutUpRight /> Export</Button></div></div><article className="data-table-card"><div className="audit-head"><span>Event</span><span>Target</span><span>Actor</span><span>Time</span><span>Result</span></div>{rows.map((op,i) => <div className="audit-row" key={i}><div className="flex items-center gap-3"><EventIcon tone={op.tone} /><div><b>{op.action}</b><span>{op.detail}</span></div></div><span>{op.user}</span><span>{op.actor}</span><span>{op.time}</span><Status label={op.tone === "warning" ? "Held" : "Success"} /></div>)}</article></div>; }

function SettingsView() { return <Tabs defaultValue="general" className="gap-5"><TabsList variant="line" className="border-b border-white/[.06]"><TabsTrigger value="general">General</TabsTrigger><TabsTrigger value="permissions">Permissions</TabsTrigger><TabsTrigger value="notifications">Notifications</TabsTrigger><TabsTrigger value="danger">Safety</TabsTrigger></TabsList><TabsContent value="general"><SettingsCard title="Workspace identity" description="How this workspace appears across Nexora Rank"><div className="grid gap-4 sm:grid-cols-2"><Field label="Workspace name" value="Brew & Co." /><Field label="Workspace slug" value="brew-and-co" /><Field label="Timezone" value="Europe/Belgrade (UTC+02)" /><Field label="Default language" value="English" /></div><Button className="button-glow mt-5" onClick={() => toast.success("Workspace settings saved.")}>Save changes</Button></SettingsCard></TabsContent><TabsContent value="permissions"><SettingsCard title="Operation permissions" description="Default protection for sensitive actions"><SettingToggle title="Require rank reasons" description="A written reason is mandatory for every manual rank change" checked /><SettingToggle title="Protect leadership ranks" description="Two authorized reviewers must approve leadership changes" checked /><SettingToggle title="Allow self-service refresh" description="Members can request their own role synchronization" checked /></SettingsCard></TabsContent><TabsContent value="notifications"><SettingsCard title="Notification preferences" description="Choose which events generate alerts"><SettingToggle title="Failed automation" description="Alert workspace owners immediately" checked /><SettingToggle title="Application ready" description="Notify reviewers when a high-score application arrives" checked /><SettingToggle title="Quota risk" description="Weekly summary for members below their activity quota" /></SettingsCard></TabsContent><TabsContent value="danger"><SettingsCard title="Safety controls" description="High-impact workspace protection"><div className="rounded-xl border border-amber-400/10 bg-amber-400/[.035] p-4"><h3 className="flex items-center gap-2 text-sm font-medium text-amber-100/70"><Pause className="size-4" /> Pause all external actions</h3><p className="mt-2 max-w-xl text-xs leading-6 text-white/30">Prevents rank changes and automation actions while preserving dashboards and audit access.</p><Button variant="outline" className="mt-4 border-amber-400/20 bg-amber-400/[.04] text-amber-200/70" onClick={() => toast.warning("External actions paused in preview mode.")}>Enable safety pause</Button></div></SettingsCard></TabsContent></Tabs>; }
function SettingsCard({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <article className="dash-card max-w-3xl"><CardHeader title={title} description={description} /><div className="mt-6">{children}</div></article>; }
function Field({ label, value }: { label: string; value: string }) { return <label><span className="mb-2 block text-xs font-medium text-white/42">{label}</span><Input defaultValue={value} className="border-white/[.08] bg-white/[.025] text-white/70" /></label>; }
function SettingToggle({ title, description, checked = false }: { title: string; description: string; checked?: boolean }) { const [state,setState]=useState(checked); return <div className="setting-toggle"><div><b>{title}</b><span>{description}</span></div><Switch checked={state} onCheckedChange={setState} aria-label={`Toggle ${title}`} /></div>; }

function OperationsTable({ compact = false }: { compact?: boolean }) { const rows=compact?operations.slice(0,4):operations; return <article className="data-table-card"><div className="p-4 sm:p-5"><CardHeader title="Recent operations" description="A live record of rank, activity, and application events" action={<button className="text-xs font-medium text-violet-300 hover:text-violet-200">View audit <ArrowRight className="ml-1 inline size-3" /></button>} /></div><div>{rows.map((op,i) => <div className="operation-row" key={i}><EventIcon tone={op.tone} /><div className="min-w-0 flex-1"><p><b>{op.user}</b> <span>{op.action.toLowerCase()}</span></p><small>{op.detail}</small></div><div className="hidden text-right sm:block"><span className="block text-[10px] text-white/28">by {op.actor}</span><time>{op.time}</time></div></div>)}</div></article>; }
function EventIcon({ tone }: { tone: string }) { const icon = tone === "warning" ? <Pause /> : tone === "info" ? <Clock3 /> : tone === "success" ? <Check /> : <MessageSquare />; return <span className={`event-icon ${tone}`}>{icon}</span>; }
function CardHeader({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold text-white/85">{title}</h2><p className="mt-1 text-[11px] text-white/28">{description}</p></div>{action}</div>; }
function MiniStat({ value,label }: { value:string;label:string }) { return <div className="mini-stat"><b>{value}</b><span>{label}</span></div>; }
function Avatar({ initials, online=false }: { initials:string; online?:boolean }) { return <span className="avatar"><span>{initials}</span>{online&&<i />}</span>; }
function Status({ label }: { label:string }) { const cls = ["Online","In game","Open","Success"].includes(label) ? "success" : ["Held","Needs discussion"].includes(label) ? "warning" : "neutral"; return <span className={`status-pill ${cls}`}><i />{label}</span>; }

function RankDialog({ trigger }: { trigger: React.ReactNode }) { const [member,setMember]=useState("MiraPlays"); const [target,setTarget]=useState("Senior Barista"); return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent className="border-white/10 bg-[#111117] text-white sm:max-w-lg"><DialogHeader><DialogTitle>New rank action</DialogTitle><DialogDescription className="text-white/40">Preview a policy-checked Roblox group rank change.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><label className="block"><span className="mb-2 block text-xs font-medium text-white/45">Member</span><select value={member} onChange={e=>setMember(e.target.value)} className="demo-select">{members.map(m=><option key={m.name}>{m.name}</option>)}</select></label><label className="block"><span className="mb-2 block text-xs font-medium text-white/45">Target rank</span><select value={target} onChange={e=>setTarget(e.target.value)} className="demo-select"><option>Barista</option><option>Senior Barista</option><option>Shift Leader</option></select></label><label className="block"><span className="mb-2 block text-xs font-medium text-white/45">Reason</span><textarea className="demo-textarea" defaultValue="Activity requirements completed and performance approved." /></label><div className="rounded-xl border border-emerald-400/10 bg-emerald-400/[.045] p-3"><p className="flex items-center gap-2 text-xs font-medium text-emerald-200/70"><ShieldCheck className="size-4" /> Policy check passed</p><p className="mt-1 text-[10px] text-white/28">Allowed path • No cooldown • Your role can request this action</p></div></div><DialogFooter><DialogClose asChild><Button variant="outline" className="border-white/10">Cancel</Button></DialogClose><DialogClose asChild><Button className="button-glow" onClick={()=>toast.success(`Preview complete: ${member} → ${target}`)}>Run safe preview <ArrowRight /></Button></DialogClose></DialogFooter></DialogContent></Dialog>; }
